global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-service:8080"]

  - job_name: "external-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["external-service:8081"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
